from .prompt import GENERATE_QUESTION_TEMPLATE,USER_TEMPLATE,QUESTION_CHANGE_TEMPLATE,COMPLETETION_QUESTION_TEMPLATE,THINK_TEMPLATE,JUDGE_TEMPLATE
__all__ = [
    "GENERATE_QUESTION_TEMPLATE",
    "USER_TEMPLATE",
    "QUESTION_CHANGE_TEMPLATE",
    "COMPLETETION_QUESTION_TEMPLATE",
    "THINK_TEMPLATE"
    "JUDGE_TEMPLATE"
]